# name -> event -> job -> runner -> steps: checkout, python, install dependencies, Lint, pytest

name: Build

on:
  push: # trigger on commit to main 
    branches: [main]
  pull_request: # or when we open, update, or synchronize a pull request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code (fetch updated code)
        uses: actions/checkout@v6.0.2

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.11

      - name: Install Dependences
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (Run Static Analysis)
        run: ruff check .  # catches things like: unused imports, undefined names, formatting/style issues; Doesn't run code

      - name: Run Test
        run: | 
          export PYTHONPATH=$(pwd) 
          pytest -vv 
        # $(pwd) points to the repo root. This ensures Python can find the app package.
        # -vv gives verbose pytest output.
